version: '3.8'

services:

  nginx-proxy:
    # docs: https://github.com/nginx-proxy/nginx-proxy/blob/main/docs/README.md
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
    volumes:
      # Config
      - ./container/nginx_proxy/addtiionals.conf:/etc/nginx/conf.d/addtiionals.conf:ro

      # Socket 
      - /run/user/1000/podman/podman.sock:/tmp/docker.sock:Z #
      # - /var/run/docker.sock:/tmp/docker.sock:ro #  on case of  use podman-docker and docker-remote

      # Lgos
      # - ./container/nginx_proxy/error.log:/var/log/nginx/error.log:Z # optional to monitor error.log
      # - ./container/nginx_proxy/access.log:/var/log/nginx/access.log:Z # optional to monitor access.log
    privileged: true
    container_name: nginx_proxy
    restart: always

  app:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./laravel-app:/var/www/html:Z
      # Inspect the var: PHP_INI_DIR in the php container to link config
      - ./container/php-fpm/additionals-php.ini:/usr/local/etc/php/conf.d/additionals-php.ini
      # - ./laravel-app:/var/www/html
    networks:
      - laravel

  webserver:
    image: nginx:latest
    container_name: nginx_server
    privileged: true
    volumes:
      - ./laravel-app:/var/www/html:Z
      - ./container/nginx/default.conf:/etc/nginx/conf.d/default.conf
    # config to vhost
    environment:
      - VIRTUAL_HOST=catspace.test
      - VIRTUAL_PORT=80
    ports:
      - "8080:80"
    networks:
      - laravel
    depends_on:
      - app
  
  dbserv:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=galery_db
      - MYSQL_USER=galery_user
      - MYSQL_PASSWORD=galery_password
    volumes:
      - ./mysql:/var/lib/mysql:z
    ports:
      - "5001:3306"
    container_name: mysql_server
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "5002:80"
    environment:
      - PMA_HOST=dbserv
      - PMA_PORT=3306
      - PMA_USER=galery_user
      - PMA_PASSWORD=galery_password
      - PMA_DATABASE=galery_db
      - MYSQL_ROOT_PASSWORD=root
      - UPLOAD_LIMIT=2048M
    container_name: phpmyadmin_server
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
